spring.application.name=cruddemo

# Datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Simple Spring Security
spring.security.user.name=san
spring.security.user.password=daniel